### ISSUE TITLE
macOS libtensorflow_cc.so has bad id

### ISSUE THREAD

**Issue by bangnoise** [memo/ofxMSATensorFlow#14]
The macOS libtensorflow 1.0 you [provide](https://github.com/memo/ofxMSATensorFlow/releases/download/tf1.0/lib_TF1.0_osx_OPT_CPU_2017_02_22.zip) has a machine-specific id

```
$ otool -L libs/tensorflow/lib/osx/libtensorflow_cc.so
libs/tensorflow/lib/osx/libtensorflow_cc.so:
	bazel-out/local-opt/bin/tensorflow/libtensorflow_cc.so (compatibility version 0.0.0, current version 0.0.0)
```
is cured by

```
install_name_tool -id libtensorflow_cc.so libs/tensorflow/lib/osx/libtensorflow_cc.so
```

**Comment by memo** [comment]
oh I didn't know that, thanks! I'm near a mac today. Do you have a URL to a cleaned lib? I can add it to the releases straight away.

**Comment by bangnoise** [comment]
[libtensorflow_cc.so.zip](https://github.com/memo/ofxMSATensorFlow/files/810611/libtensorflow_cc.so.zip)

This has the id libtensorflow_cc.so - you could also set it to @rpath/libtensorflow_cc.so and then have addon_config.mk do

```
osx:
    ADDON_LDFLAGS = -rpath @loader_path/../../../../../../../addons/ofxMSATensorFlow/libs/tensorflow/lib/osx
```

to locate it when applications are run from their usual positions (works in OF/addons and OF/apps)

**Comment by memo** [comment]
thanks. I've added the zip to the releases. 

That's a lot of ../.. ! :) Send a pull request with it if you want.
