### ISSUE TITLE
ADDON_INCLUDES_EXCLUDE in addon_config.mk

### ISSUE THREAD

**Issue by bangnoise** [memo/ofxMSATensorFlow#15]
Xcode at least requires - maybe all platforms do - :

`ADDON_INCLUDES_EXCLUDE = libs/tensorflow/include/Eigen/src/%`

**Comment by memo** [comment]
Hey, I was having a similar problem on QTCreator, and initially I was only including a few ADDON_INCLUDES paths, but then a particular version of of/qbs parser broke this. See this thread https://forum.openframeworks.cc/t/addon-not-correctly-imported-qtcreator-ubuntu/25713/17?u=memo

Though later on QTCreator at least I managed to get around this problem and removed all header include lines from the addon.mk. Though I didn't test that latest version on xcode. 

Is that one line enough to address any issues? Do you want to send a pull request with the updated addon_config.mk?
