### ISSUE TITLE
Linker error when building examples

### ISSUE THREAD

**Issue by narner** [memo/ofxMSATensorFlow#18]
Hey Memo, thanks for these examples! Looks like they're exactly what I need to help get started with TensorFlow. 

I'm trying to build the examples, but have run into some issues. I'm on macOS 10.12.4 using Xcode 8.3.2, and building with the OF Project Generator. 

I followed your instructions to make sure that `libtensorflow_cc.so` was copied in both my system lib folder, and in the addon's lib folder:

<img width="1024" alt="screen shot 2017-05-19 at 7 30 57 pm" src="https://cloud.githubusercontent.com/assets/2131591/26270555/c23c6a8e-3cc9-11e7-9d50-e4181e62b62b.png">

<img width="612" alt="screen shot 2017-05-19 at 7 29 56 pm" src="https://cloud.githubusercontent.com/assets/2131591/26270556/c23ca2ba-3cc9-11e7-8eaa-3fcc1c95dea7.png">

When I try to build the examples, I get the following linker errors:

<img width="802" alt="screen shot 2017-05-19 at 7 32 27 pm" src="https://cloud.githubusercontent.com/assets/2131591/26270579/f72c45fc-3cc9-11e7-9630-b16d1fc94499.png">

I don't think I missed a step in your installation instructions, so I'm not entirely sure what the issue is - any advice or help appreciated!

Thanks,
Nick

**Comment by memo** [comment]
Hey, unfortunately I don't have a mac anymore so I can't be too helpful. The mac lib is still for tf1.0, but the headers are for tf1.1, that could cause problems, but I don't think your problem is related to that, since really fundamental things are missing like tensorflow::Tensor::Tensor() (though maybe you could try checking out tag tf1.0?) 

Where is the second lib folder btw? is it in the root of your drive? or in your user home folder ~/lib?

**Comment by narner** [comment]
Huh, weird...the lib files I downloaded from releases were the tag [tf1.0](https://github.com/memo/ofxMSATensorFlow/releases) ones. 

Yeah, the second folder is in the root of the drive... `Macintosh HD/lib/libtensorflow_cc.so`

**Comment by QuantScientist** [comment]
Hi,
Thanks for the examples. I am on Ubuntu, I copied the tf lib (libtensorflow_cc.so) to its designated folder as instructed, and everything compiles, however during runtime the following error is thrown:

*** stack smashing detected ***: ./bin/tf_cpp_of terminated

`
rtaudio
make[2]: Entering directory '/home/dambo/Downloads/of_v0.9.8_linux64_release/apps/myApps/tf_cpp_of'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl glfw3 gl glu glew gtk+-3.0 
     compiling done
     to launch the application

     cd bin
     ./tf_cpp_of
     
     - or -
     
     make RunRelease

make[2]: Leaving directory /home/dambo/Downloads/of_v0.9.8_linux64_release/apps/myApps/tf_cpp_of
make[1]: Leaving directory /home/dambo/Downloads/of_v0.9.8_linux64_release/apps/myApps/tf_cpp_of
dambo@dambo-VirtualBox:~/Downloads/of_v0.9.8_linux64_release/apps/myApps/tf_cpp_of$ ./bin/tf_cpp_of 
2017-05-25 14:49:23.282823: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-25 14:49:23.282934: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-25 14:49:23.282975: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.

*** stack smashing detected ***: ./bin/tf_cpp_of terminated
Aborted (core dumped)
dambo@dambo-VirtualBox:~/Downloads/of_v0.9.8_linux64_release/apps/myApps/tf_cpp_of$

Any ideas what the problem may be? 
Are there any specific flags to pass during the TF build, e,g, for libtensorflow_cc.so? 

Thanks,

**Comment by memo** [comment]
@narner 
I believe on OSX you should put the library in a ~\lib folder (i.e. in your home folder, not in the root of the drive). 

@QuantScientist 
I've not encountered that problem I'm afraid! I'll need to look into it.
(btw this would be better as as separate issue. If @narner's issue is resolved, it's best to close this issue).

**Comment by narner** [comment]
Hey @memo, apologies for the late reply - I tried what you said and moved the library in ~/lib folder (screenshot below), but I ended up getting the same linker errors. I went back and re-read the installation instructions to make sure I didn't miss anything, and I don't *think* I did...

Thanks for your help!

<img width="402" alt="screen shot 2017-05-30 at 9 37 45 am" src="https://cloud.githubusercontent.com/assets/2131591/26586021/eabebc3c-451b-11e7-85cc-5d4d7288fa6e.png">

**Comment by memo** [comment]
Hi Nick, it looks like you've put it in your ~/Library folder, not ~/lib :)

**Comment by narner** [comment]
Ah, that was dumb of me :|

It looks like I can't copy the library to that folder due to permissions issues...more research needed; but seems like an issue with my system more than anything else. 

Would it make sense to download the application binaries to at least get started?

**Comment by memo** [comment]
Hi Nick, no worries, this stuff is pretty complex :S

unfortunately the binaries won't run without the lib in place, as it's a dynamic library. One of main issues is this. I couldn't figure out how to make it a static lib yet. 

I think by default there wouldn't be a lib folder in your home. So you might need to create one. If you have permission issues, you can goto the terminal and copy with the sudo command. 
sudo cp /path/to/src /path/to/dest

When using sudo be careful though! I'm not sure you'd need to use sudo for lib's in your home folder. (I don't have a mac right now so I can't test I'm afraid).

Maybe ask on OF forums.

**Comment by narner** [comment]
Ha, glad I'm not the only one who thought so :)

I created a posting on Stack Exchange [here](https://apple.stackexchange.com/questions/285362/write-write-to-usr-lib-on-macos-sierra), and the OF forums [here](https://forum.openframeworks.cc/t/adding-a-library-folder-to-usr-lib-for-ofxmastensorflow/26928).

I'll go ahead and close for now, and post again if a solution presents itself. 

Thanks!
