### ISSUE TITLE
libs missing (linux)

### ISSUE THREAD

**Issue by elliotwoods** [memo/ofxMSATensorFlow#2]
maybe you need a `git force add`?
https://github.com/memo/ofxMSATensorFlow/tree/master/libs/tensorflow/lib/linux64

**Comment by memo** [comment]
thanks for the first issue :)

I don't include any bins in the repo. I attached them as a zip in a release. I mention this in the readme but perhaps wasn't clear, I'll make it clearer.

**Comment by memo** [comment]
oh and I just realized the Release wasn't public, whoops! fixed now.
