### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by javl** [memo/ofxMSATensorFlow#21]
It seems Github doesn't allow me to fork and edit a wiki.

On the getting started page, under **Copy library and set search path**, it says:
    
    Or you can add ofxMSATensorFlow/libs/tensorflow/[linux64 or osx] to your library search path 

The path should actually read *tensorflow/**lib**/[linux64 or osx]*:

Link to page:
https://github.com/memo/ofxMSATensorFlow/wiki/Getting-started

Related pullrequest for a similar typo:
https://github.com/memo/ofxMSATensorFlow/pull/22

**Comment by memo** [comment]
well spotted! thanks :)
