### ISSUE TITLE
stdout maxBuffer exceeded.

### ISSUE THREAD

**Issue by AnasGhrab** [memo/ofxMSATensorFlow#28]
I get ```stdout maxBuffer exceeded.``` on OS X when I try to update a project with ofxMSATensorFlow using the projectGenerator.

**Comment by memo** [comment]
Hi, yes I just encountered this as well (on OSX). Not sure what the issue is. Maybe a broader issue with the project generator?

**Comment by bakercp** [comment]
This was fixed https://github.com/openframeworks/projectGenerator/issues/122

**Comment by AndresCuervo** [comment]
@AnasGhrab If you're still getting the issue in 0.9.8 on MacOS try _unchecking_ the "Verbose Output" option in the settings menu.

If you're still getting `stdout maxBuffer exceeded` then you'll need to use the command line version (here, for brevity, $OF_PATH is the path to the root of your OF folder):

`"${OF_PATH}/projectGenerator-osx/projectGenerator.app/Contents/Resources/app/app/projectGenerator" -o$OF_PATH -a"list,of,ofxAddons" -p"osx" "/path/to/project/you/want/to/addon/to"`

Note: there are no spaces between flags (e.g. `-o`, `-p`) and their arguments.
