### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by gorkacortazar** [memo/ofxMSATensorFlow#3]
Actually runs without problems on OSX.

I will try to make it compatible with the project generator during the weekend before sending a PR

**Comment by memo** [comment]
super thanks for letting me know!

**Comment by gorkacortazar** [comment]
One weird thing that is bothering me is that the shared library seems to try to load from bazel-out/local_darwin-opt/bin/tensorflow ... That means that it may need that location as a environment variable in the OS?

**Comment by barrylachapelle** [comment]
Thanks @memo looking forward to get this going. @gorkacortazar are you running through Xcode or QT?

**Comment by gorkacortazar** [comment]
@barrylachapelle Basically i did this process, in xCode:

1. Installed prerequisites for tensorflow with google instructions
2. Downloaded and compiled the tensorflow so from Memo's fork of tensorflow
3. Created a project adding the includes paths that tensorflow requires (it took a little time to figure out all)
4. Linked the resulting SO in the Xcode, adding it to the link phase and to the copy phase.
5. In the copy phase, I need to add it with the following configurations:
- Destination: Products Directory
- Subpath: bazel-out/local_darwin-opt/bin/tensorflow

That last step is annoying me, as the path seems to be hardcoded in the library, I will try to build it later this week as a Dynamic Librar to try to include it in the App Folders, but for now is working.

**Comment by Dazzid** [comment]
Hi Gorka, 
I'm trying to compile in OSX and I have doubts about the 2. Downloaded and compiled the tensorflow so from Memo's fork of tensorflow.  When I comple following TF tutorial, I get a libtensorflow_framework.1.13.1.dylib 
What should be the correct method?
