### ISSUE TITLE
library path problem QtCreator / Mac

### ISSUE THREAD

**Issue by gu-ma** [memo/ofxMSATensorFlow#7]
I have some problem when including the library in a project in QT Creator, it's probably a simple problem with the search path but I cannot figure out where this is coming from. 

Error message when compiling a program created with the project generator:
/OF/apps/playgroundApps/untitled1/src/ofApp.h:4: error: 'ofxMSATensorFlow.h' file not found
#include "ofxMSATensorFlow.h"
         ^
Error message when compiling one of the example:
/OF/addons/ofxMSATensorFlow/src/ofxMSATFIncludes.h:23: error: 'tensorflow/cc/ops/standard_ops.h' file not found
#include "tensorflow/cc/ops/standard_ops.h"

Maybe it's a pb with QT-Creator, but other addons are working fine... It was working before and for whatever reason it's not working anymore, it's working fine with XCode.

**Comment by memo** [comment]
Yes I've discovered this too and there is a post about it on the [forum](https://forum.openframeworks.cc/t/addon-not-correctly-imported-qtcreator-ubuntu/25713/17). 

I'm not sure why it's happening, but I've found  a workaround. And like I said on the forum, I'm currently updating the addon to use tensorflow v1.0, there is a lot to fix :S but hopefully soon I'll push it all.
