### ISSUE TITLE
Inception example assets

### ISSUE THREAD

**Issue by autr** [memo/ofxMSATensorFlow#8]
Hi, this error has got me stumped in Inception example in 0.9.3 and 0.9.8 - seems to be originating with the models data, perhaps a mismatch of the .txt classification names? Any help much appreciated!

![screen shot 2017-02-17 at 16 26 36](https://cloud.githubusercontent.com/assets/1035590/23119031/ca604946-f756-11e6-9a09-f5cab6c2e140.png)

**Comment by memo** [comment]
Ok thanks. I'm just updating the addon to tensorflow r1.0 and there is an awful lot to fix :S I'll have a look at this when the time comes.

**Comment by memo** [comment]
doesn't happen in current version (r1.0)
